In [ ]:
import sys
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
1.
import os  # import os module

In [24]:
PATH = Path("/home/hargy/Scientific/Projects/ND-Calibration/analysis/data/output/output_test.parquet")
df = pd.read_parquet(PATH)

In [25]:
df[(df["fX1"] > 900) & (df["isEntry"]==1)]

,eventID,pdgID,isEntry,fX1,fY1,fZ1,fX2,fY2,fZ2,fK1,fK2,fEdep
1,9448,2112,1,1017.849976,237.107025,-3.288182,1040.048340,242.523300,-3.058173,2.043194,1.340517,0.0
15,32710,2112,1,1020.056274,227.550385,9.418888,1020.317444,227.602631,9.420287,2.411719,2.411719,0.0
16,32710,22,1,1033.911377,230.677826,9.369266,1033.051147,250.792694,2.311942,0.846359,0.846359,0.0
17,32710,2112,1,1033.709473,230.605453,9.348265,1020.233948,248.055496,0.344198,1.466703,1.466703,0.0
18,36124,22,1,1018.939331,241.018539,-10.823387,1025.368896,244.886337,9.252244,2.223057,2.223057,0.0
27,51496,2112,1,1039.134033,234.321091,-10.920569,1037.753174,234.588013,-9.727489,0.023083,0.020256,0.0
35,52818,2112,1,1048.727051,229.597153,0.091063,1049.071777,229.865112,0.502164,0.000006,0.000004,0.0
41,60043,2112,1,1060.844116,249.727753,11.262811,1056.901001,253.902893,7.471675,0.262645,0.262645,0.0
45,69358,2112,1,1018.470520,234.419067,6.865667,1057.431641,243.386658,7.128310,2.445000,2.078419,0.0
48,83685,2112,1,1018.112427,235.970139,-8.092357,1045.849731,242.398880,-8.312824,2.445000,1.805488,0.0
52,86882,2112,1,1067.264771,244.449173,6.750877,1050.185791,244.838593,11.976795,0.728577,0.728577,0.0
56,115753,22,1,1019.458618,230.139236,-2.984996,1067.944580,241.505051,-2.712980,0.847000,0.847000,0.0
58,128166,2112,1,1016.282288,243.897385,-2.199748,1060.829346,254.588211,-2.296170,2.445000,2.190405,0.0
61,130420,2112,1,1015.896973,245.566406,2.310723,1064.365479,257.007568,1.889433,1.096705,1.096705,0.0
62,153085,2112,1,1048.895020,230.778030,-5.091390,1051.268677,238.297592,-0.784948,0.000017,0.000009,0.0
74,160308,2112,1,1031.130859,250.481155,1.500527,1029.067993,244.996918,5.018540,0.206555,0.135268,0.0
86,164546,2112,1,1018.104553,236.004303,-4.332604,1066.618164,247.250122,-4.539057,2.445000,2.445000,0.0
87,174668,2112,1,1016.881409,241.302216,-3.333483,1033.569946,245.272095,-3.542169,1.271011,0.292121,0.0
111,189451,2112,1,1054.012695,249.741409,-10.483863,1067.908936,241.659225,1.129507,0.937724,0.937724,0.0
116,189884,2112,1,1020.598755,225.200699,0.822288,1069.201782,236.059540,1.076497,2.301479,2.301479,0.0
117,195791,2112,1,1019.658264,229.274475,-4.280908,1024.574341,230.472458,-4.234799,2.414736,1.805426,0.0

In [26]:
df[(df["fX1"] < 700) & (df["isEntry"]==1)]

,eventID,pdgID,isEntry,fX1,fY1,fZ1,fX2,fY2,fZ2,fK1,fK2,fEdep
0,5514,22,1,543.774109,-816.522400,-4.506027,542.035645,-819.785156,9.120988,4.388895e-01,4.388895e-01,0.0
7,14838,2112,1,527.606995,-808.117859,-6.378891,549.687012,-841.945557,-4.720604,1.558813e+00,1.227921e+00,0.0
11,18577,2112,1,533.031311,-804.595215,-0.994247,555.863892,-839.060364,-1.036836,2.445000e+00,1.558520e+00,0.0
14,27371,2112,1,538.684326,-807.340210,1.778373,519.826843,-817.997925,7.591804,1.941110e+00,1.941110e+00,0.0
19,38952,2112,1,518.185303,-814.236328,-0.288657,521.598572,-819.565979,-0.259896,2.409079e+00,1.008754e+00,0.0
26,45733,2112,1,522.910339,-811.167908,-10.652460,549.224182,-853.459167,-10.576771,2.429653e+00,2.429653e+00,0.0
31,52808,2112,1,523.219299,-826.667297,-4.274567,524.815796,-825.677185,4.398569,2.088426e+00,1.501487e+00,0.0
42,67559,2112,1,551.759949,-851.812439,2.992575,542.508545,-854.190918,4.134121,6.486186e-05,4.846932e-05,0.0
53,90957,2112,1,525.089111,-809.752930,11.744084,537.479858,-829.651428,12.151030,2.439431e+00,2.439431e+00,0.0
54,90957,2112,1,540.646301,-834.638428,12.145438,555.294128,-849.517273,2.960073,2.429411e+00,2.429411e+00,0.0
55,94070,22,1,527.762573,-808.016785,-7.252467,532.129883,-810.905884,11.287028,6.199999e+00,6.199999e+00,0.0
57,120950,2112,1,522.098633,-811.695007,11.432806,522.364075,-812.078369,11.454911,5.670089e-01,5.670089e-01,0.0
71,159732,22,1,523.962585,-810.484497,0.660861,531.958557,-822.974731,1.066582,2.312096e-01,1.607197e-01,0.0
93,176691,2112,1,537.022400,-848.680298,-2.943720,543.880310,-843.985046,5.067620,2.100569e-08,2.685465e-08,0.0
98,184879,2112,1,523.004578,-811.106628,-11.070800,528.059814,-818.337646,-11.384016,1.470046e+00,1.405930e+00,0.0
110,188917,2112,1,524.379150,-810.213989,-7.920301,549.867676,-853.041260,-6.871013,1.334419e+00,1.334419e+00,0.0
112,189682,2112,1,549.455994,-843.305298,-12.105494,556.683044,-841.260071,-3.993577,4.730855e-01,5.624078e-02,0.0

In [27]:
18/14

1.2857142857142858